name: Test pull request
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: docker run -d -p 6379:6379 redis
    - uses: actions/checkout@v2.1.1
    - uses: ruby/setup-ruby@v1
    - name: Install dep gem
      run: gem install dep
    - name: Install dependencies
      run: dep install
    - name: Install dev dependencies
      run: dep -f .gems.dev install
    - name: Run tests
      run: make test
